### ISSUE TITLE
[Join Request] Add me as collaborator on BMG

### ISSUE THREAD

**Issue by F4lconer** [BSData/batman#1]
Hello,

I'd like to participate on adding Batman Miniature Game to data files for Battlescribe.

Cheers
Vaclav

**Comment by amis92** [comment]
Hello, @F4lconer. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/batman/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
